"""Pronunciation overrides for TTS (word-boundary aware)."""

from __future__ import annotations

import re

# Longer phrases first when applying. Avoid dotted initialisms: Chatterbox often
# treats periods as sentence boundaries and Whisper then hears odd fragments.
PRONUNCIATIONS: list[tuple[str, str]] = [
    ("SaaS", "sass"),
    ("SaaStr", "sass-ter"),
    ("SaaStock", "sass stock"),
    ("SaaSBoomi", "sass boomi"),
    ("SaaSacre", "sass-acre"),
    ("SaaShimi", "sass shimi"),
    ("pureXML", "pure X M L"),
    ("XMLQUERY", "X M L Query"),
    ("XMLDATA", "X M L Data"),
    ("RDBMSweb", "R D B M S web"),
    ("DBMSroulette", "D B M S roulette"),
    ("DBMS2", "D B M S two"),
    ("RDBMS", "R D B M S"),
    ("RDBMSs", "R D B M S's"),
    ("ODBMS", "O D B M S"),
    ("ODBMSs", "O D B M S's"),
    ("DBMS", "D B M S"),
    ("DBMSs", "D B M S's"),
    ("XQuery", "X Query"),
    ("xQuery", "X Query"),
    ("XPath", "X Path"),
    ("XML", "X M L"),
    ("NoSQL", "No S Q L"),
    ("DB2", "D B two"),
    ("BLOBs", "blobs"),
    ("BLOB", "blob"),
    ("CLOBs", "clobs"),
    ("CLOB", "clob"),
    ("MarkLogic", "Mark Logic"),
    ("LinkedIn", "Linked In"),
    ("LogMeIn", "Log Me In"),
    ("MapReduce", "Map Reduce"),
    ("MongoDB", "Mongo D B"),
    ("Neo4j", "Neo four J"),
    ("QlikTech", "Click Tech"),
    ("QlikView", "Click View"),
    ("TechCrunch", "Tech Crunch"),
    ("VentureBeat", "Venture Beat"),
    ("WriteWeb", "Write Web"),
    ("BusinessObjects", "Business Objects"),
    ("OpenTable", "Open Table"),
    ("RedHat", "Red Hat"),
    ("RevOps", "Rev Ops"),
    ("ServiceNow", "Service Now"),
    ("SmartRecruiters", "Smart Recruiters"),
    ("RFID", "R F I D"),
    ("OLAP", "O L A P"),
    ("S-1", "S one"),
    ("S1", "S one"),
    ("R40", "Rule of 40"),
    ("FY12", "fiscal year twelve"),
    ("Q3", "Q three"),
    ("20VC", "twenty V C"),
    ("OnlyCFO", "Only C F O"),
    ("A16Z", "A sixteen Z"),
    ("T2D3", "T two D three"),
    ("T25", "T twenty five"),
    ("VC1", "V C one"),
    ("VC2", "V C two"),
    ("NTM", "N T M"),
    ("FTM", "F T M"),
    ("TTM", "T T M"),
    ("TTCV", "T T C V"),
    ("DOCX", "D O C X"),
    ("DOCX's", "D O C X's"),
    ("PDFs", "P D F's"),
    ("PDF", "P D F"),
    ("BANT", "B A N T"),
    ("EIRs", "E I R's"),
    ("EIR", "E I R"),
    ("E M E A", "E M E A"),
    ("EMEA", "E M E A"),
    ("UCLA", "U C L A"),
    ("NYC", "N Y C"),
    ("IFRS", "I F R S"),
    ("SIGMOD", "S I G M O D"),
    ("VLDB", "V L D B"),
    ("CACM", "C A C M"),
    ("B2B", "B to B"),
    ("B2C", "B to C"),
    ("AA", "A A"),
    ("AAA", "A A A"),
    ("AE", "A E"),
    ("AMA", "A M A"),
    ("AOL", "A O L"),
    ("BOBJ", "B O B J"),
    ("BCG", "B C G"),
    ("ACID", "acid"),
    ("ACV", "A C V"),
    ("ACD", "A C D"),
    ("ASC", "A S C"),
    ("AEs", "A E's"),
    ("AE", "A E"),
    ("AR", "A R"),
    ("ASK", "ask"),
    ("CDC", "C D C"),
    ("CDG", "C D G"),
    ("CET", "C E T"),
    ("CDOs", "C D O's"),
    ("CDO", "C D O"),
    ("CSAT", "C SAT"),
    ("CSMs", "C S M's"),
    ("CSM", "C S M"),
    ("CS", "C S"),
    ("CTA", "C T A"),
    ("COGS", "C O G S"),
    ("COVID", "covid"),
    ("CIO", "C I O"),
    ("CMS", "C M S"),
    ("COO", "C O O"),
    ("CPG", "C P G"),
    ("CSP", "C S P"),
    ("CXOs", "C X O's"),
    ("CXO", "C X O"),
    ("EII", "E I I"),
    ("BI", "B I"),
    ("CAC", "C A C"),
    ("NRR", "N R R"),
    ("ATR", "A T R"),
    ("EPM", "E P M"),
    ("ABM", "A B M"),
    ("LTV", "L T V"),
    ("MQL", "M Q L"),
    ("MQLs", "M Q L's"),
    ("TCV", "T C V"),
    ("GAAP", "G A A P"),
    ("MBA", "M B A"),
    ("ASP", "A S P"),
    ("CPP", "C P P"),
    ("ECM", "E C M"),
    ("EMC", "E M C"),
    ("SAP", "S A P"),
    ("IBM", "I B M"),
    ("HP", "H P"),
    ("CTO", "C T O"),
    ("CMMI", "C M M I"),
    ("CA", "California"),
    ("CCS", "C C S"),
    ("CG", "C G"),
    ("C3", "C three"),
    ("DEVs", "devs"),
    ("DK", "D K"),
    ("EBITDA", "E B I T D A"),
    ("ERG", "E R G"),
    ("ETL", "E T L"),
    ("FAST", "Fast"),
    ("FBI", "F B I"),
    ("FCF", "F C F"),
    ("FLS", "F L S"),
    ("FP", "F P"),
    ("GC", "G C"),
    ("GE", "G E"),
    ("G2", "G two"),
    ("GMs", "G M's"),
    ("GM", "G M"),
    ("GRR", "G R R"),
    ("HBR", "H B R"),
    ("HBSP", "H B S P"),
    ("HG", "H G"),
    ("HR", "H R"),
    ("IDC", "I D C"),
    ("IC", "I C"),
    ("II", "two"),
    ("III", "three"),
    ("IMHO", "I M H O"),
    ("IMS", "I M S"),
    ("IRR", "I R R"),
    ("ISO", "I S O"),
    ("IP", "I P"),
    ("JMP", "J M P"),
    ("JPK", "J P K"),
    ("KBCM", "K B C M"),
    ("KM", "K M"),
    ("MBAs", "M B A's"),
    ("MBA", "M B A"),
    ("MDM", "M D M"),
    ("MIT", "M I T"),
    ("MS", "M S"),
    ("MTV", "M T V"),
    ("MVP", "M V P"),
    ("MM", "M M"),
    ("NEA", "N E A"),
    ("NDR", "N D R"),
    ("NED", "N E D"),
    ("OTE", "O T E"),
    ("OK", "okay"),
    ("PC", "P C"),
    ("PDQ", "P D Q"),
    ("PEG", "P E G"),
    ("PMF", "P M F"),
    ("PMs", "P M's"),
    ("PNC", "P N C"),
    ("PT", "P T"),
    ("QBRs", "Q B R's"),
    ("QBR", "Q B R"),
    ("QCRs", "Q C R's"),
    ("QCR", "Q C R"),
    ("QED", "Q E D"),
    ("PS", "P S"),
    ("RBC", "R B C"),
    ("RAG", "R A G"),
    ("RIP", "R I P"),
    ("RPO", "R P O"),
    ("RSUs", "R S U's"),
    ("RREs", "R R E's"),
    ("RRE", "R R E"),
    ("SAA", "S A A"),
    ("SAL", "S A L"),
    ("SALs", "S A L's"),
    ("SCs", "S C's"),
    ("SC", "S C"),
    ("SEC", "S E C"),
    ("SEO", "S E O"),
    ("SFA", "S F A"),
    ("SMB", "S M B"),
    ("SIG", "S I G"),
    ("SLS", "S L S"),
    ("STP", "S T P"),
    ("SVB", "S V B"),
    ("SVP", "S V P"),
    ("SV", "S V"),
    ("SOX", "socks"),
    ("TAM", "T A M"),
    ("TCO", "T C O"),
    ("TBH", "T B H"),
    ("TV", "T V"),
    ("HIT", "hit"),
    ("MISS", "miss"),
    ("UI", "U I"),
    ("DC", "D C"),
    ("ZL's", "Z L's"),
    ("ZL", "Z L"),
    ("US", "U S"),
    ("USA", "U S A"),
    ("UK", "U K"),
    ("IT", "I T"),
    ("AM", "A M"),
    ("PM", "P M"),
    ("ARR", "A R R"),
    ("MRR", "M R R"),
    ("ICP", "I C P"),
    ("CRO", "C R O"),
    ("CROs", "C R O's"),
    ("CMO", "C M O"),
    ("CMOs", "C M O's"),
    ("CFO", "C F O"),
    ("CFOs", "C F O's"),
    ("GTM", "G T M"),
    ("OKR", "O K R"),
    ("OKRs", "O K R's"),
    ("PMM", "P M M"),
    ("GSI", "G S I"),
    ("RTO", "R T O"),
    ("TLA", "T L A"),
    ("TLAs", "T L A's"),
    ("GenAI", "Gen A I"),
    ("AI", "A I"),
    ("ML", "M L"),
    ("CEO", "C E O"),
    ("CEOs", "C E O's"),
    ("CPO", "C P O"),
    ("VP", "V P"),
    ("VPs", "V P's"),
    ("VC", "V C"),
    ("VCs", "V C's"),
    ("PE", "P E"),
    ("M&A", "M and A"),
    ("IPO", "I P O"),
    ("IPOs", "I P O's"),
    ("API", "A P I"),
    ("APIs", "A P I's"),
    ("ROI", "R O I"),
    ("KPI", "K P I"),
    ("KPIs", "K P I's"),
    ("NPS", "N P S"),
    ("SDR", "S D R"),
    ("SDRs", "S D R's"),
    ("SQL", "S Q L"),
    ("SQLs", "S Q L's"),
    ("CRM", "C R M"),
    ("ERP", "E R P"),
    ("PLG", "P L G"),
    ("PLM", "P L M"),
    ("FAQ", "F A Q"),
    ("PR", "P R"),
    ("EV", "E V"),
    ("CPO", "C P O"),
    ("CPOs", "C P O's"),
]


def apply_glossary(text: str) -> str:
    result = text
    for term, spoken in sorted(PRONUNCIATIONS, key=lambda x: -len(x[0])):
        pattern = re.compile(r"\b" + re.escape(term) + r"\b")
        result = pattern.sub(spoken, result)
    return result
